apiVersion: customFunction
kind: ClusterConfigHashGenerator
metadata:
  name: omni-cluster-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./plugins/generate-cluster-config.sh
spec:
  configPath: patches
  outputPath: ../../../../../manifests/scots-lab/cluster/omni